### ISSUE TITLE
API rework

### ISSUE THREAD

**Issue by puzrin** [Ralim/usb-pd#2]
**Goal:**

- Create lightweight USB-PD library, suitable for majority of oss projects needs (SINK mode only).

**Desired features:**

- No RTOS need if possible
- Only single SINK port support (no DRP & power rebalancing)
- Only FSUSB302 support at MVP
- Possibility to extend with STM32G0/4 built-in PD hardware in future
- PlatformIO support
- (?) Examples
  - how to create simple PD trigger for fixed profile.

**Proposed API**

TBD

**Comment by puzrin** [comment]
**References** (just a dev memo, to save time for info search)

Specs:

- USB power Delivery - https://www.usb.org/documents?search=power+delivery&items_per_page=50
- Transport interface specification - https://www.usb.org/usb-charger-pd

Stacks:

- Google
  - https://chromium.googlesource.com/chromiumos/platform/ec/+/master/driver/tcpm/fusb302.c
  - https://chromium.googlesource.com/chromiumos/platform/ec/+/firmware-twinkie-9628.B/common/ (usb_pd_*)
- STM (blobs): https://github.com/st-one/X-CUBE-USB-PD (aslo available as CubeMX Middleware, more fresh)
- On Semi: https://github.com/tatulea/FUSB302_ESP32
- Microchip: https://github.com/MicrochipTech/usb-pd-software-framework

Some OSS projects:

- [USB buddy sink](https://www.tindie.com/products/clarahobbs/pd-buddy-sink/)
- [USB C Explorer](https://github.com/ReclaimerLabs/USB-C-Explorer)

Uncertain:

- https://github.com/usb-c/STUSB1602 - some old code in in `./archive` with MIT license (they closed sources at some moment and distrubute blobs only now).

**Comment by puzrin** [comment]
@Ralim, AFAIK ST lib requires info from ADC (with real voltage value) to compensate cable losses in PPS mode. Should i reserve this feature in API or we leave it to user side?

IMO, not needed. When user needs PPS mode, he already has PID in application.

**Comment by Ralim** [comment]
So the main blocker for ST support is their blobiness; while I _think_ there is enough data published to be able to add support for it as a PHY for an alternative to the FUSB302, while ST believes in only distributing a blob, I would preference other vendors first as debugging the solution would be far easier.

Otherwise commenting to note that there is a new branch slowly coming together that breaks out a lot of the dependencies that were there before into not being required or external to the code.
Definitely still WiP, have some good time to finish up the basic testing, but also using this as a time to put some moderate testing around the "core" so that a basic testing of other PHY's _could_ be started without hardware.

Would be open to any comments on it. Cant promise I have the time to _fix_ them yet 😂  But would love to hear in case they are easier to use. I'm hoping the updated API is much easier to integrate. It does however mean it wouldn't be "drop in" for most builds, but should be relatively simple to get going (thinking worst case 4 stub functions to remap). 


Also as a _tiny_ thing, please dont use the masculine _he_ as a default when referring to other users of software, if you can. Would prefer to be inclusive 😁

**Comment by puzrin** [comment]
To be honest, i believe FUSB302 will be enough for 5+ next years, and it still has no alternative if we speak about price. But use of stm32gXXX allows simplify hardware. If we count all factors (price, afailability, comfort) - stm32g looks like next candidate after FUSB302. I don't mean you "should" support it. I mean "someone may wish to add support is lib if flexible enough"

> 2. Can i rely on hardware support for i2c (via DMA/interrupts)? Or manual bit banging of pins should be supported too?
>    - I would prefer to rely on hardware support only.

Could you comment this question? Can we rely on block transfers via DMA (or IRQ on each byte) or manual transfer on bit level with blocking delay loops should be supported too?

**Comment by Ralim** [comment]
> To be honest, i believe FUSB302 will be enough for 5+ next years, and it still has no alternative if we speak about price. But use of stm32gXXX allows simplify hardware. If we count all factors (price, afailability, comfort) - stm32g looks like next candidate after FUSB302. I don't mean you "should" support it. I mean "someone may wish to add support if library api is flexible enough"

Yes I agree, though TI and NXP have options too, so curious to see what the market does over time as well.

> 
> > 1. Can i rely on hardware support for i2c (via DMA/interrupts)? Or manual bit banging of pins should be supported too?
> >    
> >    * I would prefer to rely on hardware support only.
> 
> Could you comment this question? Can we rely on block transfers via DMA (or IRQ on each byte) or manual transfer on bit level with blocking delay loops should be supported too?

At the _moment_ you dont _require_ an IRQ, you could poll. But I would highly recommend it.

In terms of the I2C transfer method, my view is that you should be using IRQ or DMA driven transfers, but the user is free to implement whatever they wish.
In general reads are expected to be blocking, but writes can generally be async.
You could definitely be smart with the read implementation to not have to use blocking logic (read it before irq callback) but that is a user decision to make.

**Comment by puzrin** [comment]
Probably i expressed my question not enough well. If user wish to use polling on byte-level OR has no hadware implentation for communication transport (usually i2c) that will make design of universal api very inconvenient or even impossible without RTOS.

So, if we drop RTOS requirement:

1. Having hardware i2c (transport) with interrupts is minimal requirement (mandatory)
2. Having hardware i2c with DMA block transfer is highly recommended (but not mandatory)

Is this acceptable? I mean, do you have real hardware without i2c where USB-PD still MUST be supported.

IMO, in modern world, having i2c + DMA is not a problem at all. But i have no details about all devices where you may wish to support your IronOS.

**Comment by Ralim** [comment]
Ah,
So while I'm all for having it work without an RTOS (I believe this is done now). I view the task of managing an i2c implementation beyond the scope of this code.

It doesn't care _how_ the read and write functions work, but I don't believe handing callbacks for read and write to allow those to be "more" flexible is worth it. It will add a chunk more complexity for a very small subset of users. I haven't seen a micro without i2c support with IRQ or DMA unless your bit banging, and then it's a moot point anyway as it's going to be blocking or very IRQ heavy _anyway_.


As far as IronOS is concerned there will always be an RTOS around, but bit banging/IRQ/DMA all work so eh.

Even without and RTOS, it's fairly easy to have user code that handles the i2c however is wanted and then suits this API, or the user can implement their own fusb302 layer however they wish.

**Comment by puzrin** [comment]
When library architecture is designed (including API & internals design), we MUST have certain guarantees. I mean "implementing i2c drivers on desired devices should be possible and work as expected".

There is a principle architecture choice to do:

- RTOS-based
  - Simle user code, but inconvenient user project requirement (RTOS) 
- Protothread-based
  - Almost as simple as RTOS, but yielding should be restricted (lowest level [transport] should be non-blocking)
  - More friendly to user's projects (not forces RTOS use when not desired)
- Completely manual implementation of internal state machine (see On Semi link above)
  - very high complexity of library code & difficult to maintain

This can not be changed on the fly, and should be desided before diving more deep. My personal choice is "Protothread-based", as reasonable balance for [simplicity + flexibility]. With this restrictions:

- If transport driver is IRQ or DMA based, it's "non blocking" =>
  -  i can predict correct work.
- If transport driver implementation is "manual" (polling + delay loops + yielding) =>
  -  i can not predict correct work.

This is abstract logic, without thoughts about concrete hardware. BUT, if you know concrete projects, where bitbanging MUST be used, that may be a real problem for protothreads. So, i'm asking if you already have such projects or not. That's important for decision.

**Comment by Ralim** [comment]
Ah okay I think I'm not quite answering you correctly.

Yes bitbanging code must be supported.(IronOS TS80P)
Yes RTOS must be supported.(IronOS)
Also GCC8 must be supported.(Third party compilers)

Have you looked at the new branch?

The state machine is now single iteration per call, so you can add all of the yield or waits _outside_ of the library.

**Comment by puzrin** [comment]
> Have you looked at the new branch?
> 
> The state machine is now single iteration per call, so you can add all of the yield or waits _outside_ of the library.

Looks promissing. As far as i understand, you removed RTOS requirements on top level (via `::thread()` / `waitForEvent(...)` / `::getTimeStamp()`). But RTOS still required due `FUSB::...` methods calls.

If you match every current `FUSB::...` method with something like `waitForCompleteXXX`, then RTOS will be not mandatory at all.

**Comment by Ralim** [comment]
> > Have you looked at the new branch?
> > The state machine is now single iteration per call, so you can add all of the yield or waits _outside_ of the library.
> 
> Looks promissing. As far as i understand, you removed RTOS requirements on top level (via `::thread()` / `waitForEvent(...)` / `::getTimeStamp()`). But RTOS still required due `FUSB::...` methods calls.

Correct, the core USB-PD part of this project is RTOS free / RTOS agnostic.


> 
> If you match every current `FUSB::...` method with something like `waitForCompleteXXX`, then RTOS will be not mandatory at all.

There is no requirement for writes to block (you could kick it off via dma or i2c and return).
For reads, that is left up to the user. If you had to support this without protothreads or an rtos then you would want to implement your own code for the FUSB. Also keeping in mind you dont have much time (<15ms on some chargers) for the entire read+process+respond cycle. So its not like you can trivially support all drivers with just basic main loop code without being careful.

I do not see a nice way to expand the FUSB to have the extra states without adding more states to the upper PD code, which is not something that I'm willing to add for now, given that most users fall into either:
* Using RTOS or proto threads
* Using blocking calls
* Knows how to modify the FUSB driver to suit their exact application

**Comment by puzrin** [comment]
I don't understand you. I'm a concrete user who wish to avoid RTOS. Can you provide example of non-blocking FUSB driver for my case (with hardware i2c)? I don't see technical possibility to implement that without extra states.

> Only real reason I would be inclined to add waitForCompleteXXX is if there is a way to add them in a manner where they are completely removed by the compiler if you are using an RTOS. Otherwise the overhead is a waste of time for most implementations

Of cause, if user wish to use RTOS, those `waitForCompleteXXX` can be dummy functions & Read/Write can be written in sync manner as now. But without RTOS extra states required to wait until i2c exchange done.

Those extra states can be guarded by `#ifdef`, but IMO cost of dummy content is about zero. Anyway, i see no principal problem to completely remove those states via directive if you wish.

**Comment by Ralim** [comment]
Keep in mind longest transfer is like 26 bytes; at 1MHz bus rate this takes less than one millisecond.
For a _lot_ of use cases the scheduling you are using is slower at changing than that _anyway_.

If I were implementing this without an RTOS I would:
* Write -> Just shove to the peripheral with DMA and walk away
* Read -> Have my own function for the IRQ that one an IRQ does:
* - Read interrupt status regs
* - Drains FiFo into a buffer
* - Calls the IRQ callback
* - In the read handler redirect to cached values

Can you please explain your application where you want to use USB-PD, with real-time like scheduling without an RTOS?

**Comment by puzrin** [comment]
> Can you please explain your application where you want to use USB-PD, with real-time like scheduling without an RTOS?

Current application -  [mini reflow table](https://github.com/puzrin/reflow_micro/blob/master/doc/assembly.md). I don't use RTOS because has no need for it. [ETL](https://github.com/ETLCPP/etl) solves all my needs about messaging and so on.

Usually, all timer-related things are pinned to common 1ms timer. If some handler is blocking, it will have to use separate timer. Not a big deal, but looks ugly :).

---

In my eyes,  you did 90% of code cleanup from RTOS. And removing the rest should not be difficult. But probably i miss something about code complexity.

From the other hand, requirement to have separate timer + 1ms random lags (for RTOS-less variant) is acceptable for my current needs. If you don't like my proposal for some reasons - we can postpone this talk to v2.

**Comment by Ralim** [comment]
For your application, just don't use PPS, and then there is zero bus traffic after initial negotiation 😅
If you do use PPS, you have total control of when the load occurs, and you have a 10 second window to perform that in, so it should be trivial to have a state in your internal state machine to handle it with little effort.

Mostly I don't want coupling between the PD state machine and the FUSB, as the FUSB driver should handle its own comms. For future expansion, the less the pd state machine knows of hardware the better. I don't like the idea of having to have a bunch of extra states to manage if we are waiting for status read or fifo read, since different PHY's will need different number of states for this. And I'm already looking into other brands, to see what their offering is like.


In a bit of (very, very rough) testing I did at one point, running at 1Mhz for the bus and blocking was on same order of magnitude as doing DMA setup, callback, IRQ, thread notification. Thus was partly due to bad DMA driver stack (ST) but also just due to a set of irqs firing and communication.

If your building anything that's temperature controlled, I would recommend decoupling all other functions from your core PID.. but that's just me :)

**Comment by Ralim** [comment]
I should add, I'm not trying to fight with you, just trying to understand the issue, since it expands complexity for implementation and debugging for a situation i haven't come across in a long time.

Please understand I don't mean any of this to be rude ☺️

**Comment by puzrin** [comment]
> I should add, I'm not trying to fight with you, just trying to understand the issue, since it expands complexity for implementation and debugging for a situation i haven't come across in a long time.

Sometime i also have to do choice between "ideal" and "possible within available time limits" :). With blocking code, it will be less convenient to use lib without rtos. But, as i said above, 1ms lags + separate timer is acceptable for my concrete project.

**Comment by puzrin** [comment]
https://github.com/Ralim/usb-pd/blob/main/lib/Logic/int_n.cpp shouldn't content of this file be a part of driver somehow? It looks strange when part of policy engine is implemented in separate file.

IMO interrupts are specific for concrete chip driver. It should know how to handle those and what message to emit (from transport to upper level of policy engine). Or do i miss something?

**Comment by Ralim** [comment]
I agree that int_n should be folded in. Have been doing this a chunk at a time so missed it :) 

Eventually yes it needs to be cleaned up and moved into the FUSB302 code base. I don't have infinite time, so I just pick this up and work on it when I have a spare hour or so.

**Comment by Ralim** [comment]
int_n folded in now.

It _should_ be part of the driver code probably, but doing that later on

**Comment by puzrin** [comment]
Can i close this?

As far as i understand, all urgent points we solved:

- Mode without RTOS looks realistic.
- i2c fns without RTOS will be blocking, but that's not fatal (timings discussed).
- osDelay without RTOS will be blocking, but that's not critical.

Also, things above is possible to refactor without "rewrite everything", if anyone wish to spend time for this (=> never :rofl: ).

**Comment by Ralim** [comment]
I'm ok with this being closed.

Definitely all remaining work falls into the "when time permits" category.
